version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - library-network
    depends_on:
      - gateway
      - user-service
      - book-service
      - loan-service
  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - BOOK_SERVICE_URL=http://book-service:5002
      - LOAN_SERVICE_URL=http://loan-service:5003
    networks:
      - library-network
    depends_on:
      - user-service
      - book-service
      - loan-service

  user-service:
    build:
      context: ./User
      dockerfile: Dockerfile
    image: userapp:1.0
    expose:
      - "5001"
    env_file:
      - ./User/.env
    environment:
      - DB_HOST=host.docker.internal
      - USER_SERVICE_URL=http://user-service:5001
      - BOOK_SERVICE_URL=http://book-service:5002
      - LOAN_SERVICE_URL=http://loan-service:5003
    networks:
      - library-network

  book-service:
    build:
      context: ./Book
      dockerfile: Dockerfile
    image: bookapp:1.0
    expose:
      - "5002"
    env_file:
      - ./Book/.env
    environment:
      - DB_HOST=host.docker.internal
      - USER_SERVICE_URL=http://user-service:5001
      - BOOK_SERVICE_URL=http://book-service:5002
      - LOAN_SERVICE_URL=http://loan-service:5003
    networks:
      - library-network
    depends_on:
      - user-service

  loan-service:
    build:
      context: ./Loan
      dockerfile: Dockerfile
    image: loanapp:1.0
    expose:
      - "5003"
    env_file:
      - ./Loan/.env
    environment:
      - DB_HOST=host.docker.internal
      - USER_SERVICE_URL=http://user-service:5001
      - BOOK_SERVICE_URL=http://book-service:5002
      - LOAN_SERVICE_URL=http://loan-service:5003
    networks:
      - library-network
    depends_on:
      - user-service
      - book-service

networks:
  library-network:
    driver: bridge